<?= '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"<?= ($has_image?' xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"':'') ?>>
    <?php foreach($pages as $page): ?>
    <url>
        <loc><?= $page->url ?></loc>
        <lastmod><?= $page->lastmod ?></lastmod>
        <changefreq><?= $page->changefreq ?></changefreq>
        <priority><?= $page->priority ?></priority>
        <?php if(isset($page->image)): ?>
        <image:image>
            <image:loc><?= $page->image->url ?></image:loc>
            <?php if(isset($page->image->caption)): ?>
            <image:caption><?= $page->image->caption ?></image:caption>
            <?php endif; ?>
            <?php if(isset($page->image->title)): ?>
            <image:title><?= $page->image->title ?></image:title>
            <?php endif; ?>
        </image:image>
        <?php endif; ?>
    </url>
    <?php endforeach; ?>
</urlset>